apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-logs
  namespace: openstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
