apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vg1
        fstype: xfs
        default: true
        thinPoolConfig:
          name: thin-pool-1
          sizePercent: 90  
          overprovisionRatio: 10
        deviceSelector:
          paths:
            - /dev/sda5  
