apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "eno5np0.40",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.57.0/24",
        "range_start": "192.168.57.150",
        "range_end": "192.168.57.190"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storagemgmt
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storagemgmt",
      "type": "macvlan",
      "master": "eno5np0.40",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.61.0/24",
        "range_start": "192.168.61.150",
        "range_end": "192.168.61.190"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "macvlan",
      "master": "eno5np0.30",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.58.0/24",
        "range_start": "192.168.58.150",
        "range_end": "192.168.58.190"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "macvlan",
      "master": "eno5np0.60",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.59.0/24",
        "range_start": "192.168.59.150",
        "range_end": "192.168.59.190"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "macvlan",
      "master": "eno5np0.50",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.60.0/24",
        "range_start": "192.168.60.150",
        "range_end": "192.168.60.190"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: management
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "management",
      "type": "macvlan",
      "master": "br-ex",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.56.0/24",
        "range_start": "192.168.56.100",
        "range_end": "192.168.56.150"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-mgmt
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vm-mgmt",
      "type": "bridge",
      "bridge": "br-mgmt",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.56.0/24",
        "range_start": "192.168.56.151",
        "range_end": "192.168.56.200"
      }
    }
