apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: openstack
spec:
  networks:
  - name: external
    dnsDomain: external.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.56.0/24
        gateway: 192.168.56.254
        allocationRanges:
          - start: 192.168.56.200
            end: 192.168.56.249
  - name: ctlplane
    dnsDomain: ctlplane.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.58.0/24
        gateway: 192.168.58.254
        allocationRanges:
          - start: 192.168.58.200
            end: 192.168.58.249
        vlan: 30
  - name: internalapi
    dnsDomain: internalapi.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.57.0/24
        gateway: 192.168.57.254
        allocationRanges:
          - start: 192.168.57.200
            end: 192.168.57.249
        vlan: 40
  - name: storage
    dnsDomain: storage.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.59.0/24
        gateway: 192.168.59.254
        allocationRanges:
          - start: 192.168.59.200
            end: 192.168.59.249
        vlan: 60
  - name: tenant
    dnsDomain: tenant.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.60.0/24
        gateway: 192.168.60.254
        allocationRanges:
          - start: 192.168.60.200
            end: 192.168.60.249
        vlan: 50
  - name: storagemgmt
    dnsDomain: storagemgmt.imlab.priv
    subnets:
      - name: subnet1
        cidr: 192.168.61.0/24
        gateway: 192.168.61.254
        allocationRanges: 
          - start: 192.168.61.200
            end: 192.168.61.249
        vlan: 70

