- name: Install chrony package
  ansible.builtin.yum:
    name: chrony
    state: present

- name: Configure chronyd
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start chronyd service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes

